/**
 * Fetches the top crypto symbols by market cap from CoinGecko and generates
 * src/parsers/crypto-symbols.ts. Run manually or in CI to keep the list fresh.
 *
 * Usage: npx tsx scripts/update-crypto-symbols.ts
 *
 * CoinGecko's free API requires no key. Rate limit: ~30 req/min.
 * We fetch top 500 coins by market cap — covers everything any retail
 * exchange (Revolut, eToro, etc.) could realistically offer.
 */

const COINGECKO_URL = "https://api.coingecko.com/api/v3/coins/markets";
const PAGES = 2; // 250 per page × 2 = 500 coins
const PER_PAGE = 250;
const OUTPUT_PATH = "src/parsers/crypto-symbols.ts";

// Symbols that exist as both crypto AND stock tickers — on retail brokers like
// Revolut these are overwhelmingly stocks. Exclude from the crypto set so the
// parser defaults them to STK (the correct behavior for Revolut users).
const STOCK_TICKER_CONFLICTS = new Set([
  "A", "B", "C", "D", "F", "G", "K", "T", "V", "X",
  "AA", "AB", "AG", "AI", "AL", "AM", "AN", "AR", "AS", "AT", "AU", "AV",
  "BA", "BP", "BT", "DB", "GE", "GM", "HP",
  // Listed US shares and ETFs whose ticker is also a coin symbol
  "H", "M", "S", "U", "W",
  "GT", "IP",
  "AMP", "BIO", "LIT", "MET", "TEL", "VVV",
  "BEAM", "BILL", "CASH", "META",
]);

async function fetchPage(page: number): Promise<string[]> {
  const url = `${COINGECKO_URL}?vs_currency=usd&order=market_cap_desc&per_page=${PER_PAGE}&page=${page}&sparkline=false`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`CoinGecko API error: ${res.status} ${res.statusText}`);
  const data = (await res.json()) as Array<{ symbol: string }>;
  return data.map((coin) => coin.symbol.toUpperCase());
}

async function main() {
  const allSymbols = new Set<string>();

  for (let page = 1; page <= PAGES; page++) {
    const symbols = await fetchPage(page);
    for (const s of symbols) allSymbols.add(s);
    if (page < PAGES) await new Promise((r) => setTimeout(r, 1500));
  }

  // Filter: alphanumeric 1-10 chars, exclude known stock ticker conflicts
  const filtered = [...allSymbols]
    .filter((s) => /^[A-Z0-9]{1,10}$/.test(s) && !STOCK_TICKER_CONFLICTS.has(s))
    .sort();

  // Format as TypeScript
  const lines: string[] = [];
  lines.push("// Auto-generated by scripts/update-crypto-symbols.ts — do not edit manually.");
  lines.push(`// Last updated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`// Source: CoinGecko top ${PAGES * PER_PAGE} coins by market cap`);
  lines.push("//");
  lines.push("// Run: npx tsx scripts/update-crypto-symbols.ts");
  lines.push("");
  lines.push("export const KNOWN_CRYPTO_SYMBOLS = new Set([");

  // Write in rows of 10 for readability
  for (let i = 0; i < filtered.length; i += 10) {
    const chunk = filtered.slice(i, i + 10).map((s) => `"${s}"`).join(", ");
    lines.push(`  ${chunk},`);
  }

  lines.push("]);");
  lines.push("");

  const { writeFileSync } = await import("fs");
  const { resolve } = await import("path");
  const outPath = resolve(process.cwd(), OUTPUT_PATH);
  writeFileSync(outPath, lines.join("\n"));

  console.log(`✓ Wrote ${filtered.length} crypto symbols to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("Failed to update crypto symbols:", err);
  process.exit(1);
});
